### ISSUE TITLE
Move to MiSTer-devel

### ISSUE THREAD

**Issue by sorgelig** [Ace9921/Arcade-Arkanoid_MISTer#2]
Hi!

I'm a big fan of Arcanoid game and glad to see this arcade implemented on MiSTer!
Can you move this repository to MiSTer-devel and continue to develop there?
I've made invitation for you. After accepting it you can create/fork your repository there.

**Comment by Ace9921** [comment]
Repository has just been forked.  Shall I add a Wiki entry for Arkanoid as well while I'm at it?

**Comment by sorgelig** [comment]
yes, please

**Comment by Ace9921** [comment]
Done.  Anything else you need from me, just let me know.

**Comment by sorgelig** [comment]
ok. Thanks!
