### ISSUE TITLE
Reverse Dial Spinner Option

### ISSUE THREAD

**Issue by neosquid** [Ace9921/Arcade-Arkanoid_MISTer#3]
Hi, 

Could it be possible to add a "Reverse Dial" control option as found in MAME Arkanoid?

In MiSTer Arkanoid, my Spinner control sends the bat right when I turn my spinner left, and the bat left when I turn the Spinner right.

Thanks

**Comment by sorgelig** [comment]
MiSTer uses same direction for all cores supporting Spinner. 
Better to swap 2 wires in your spinner, so it will work as expected with all cores.

**Comment by dfilskov** [comment]
Will swapping the cables on our GRS spinners work?

However, it seems a cumbersome to "quickly" swap cables when two players are using the spinner between games or alternately as player 1 and 2 and prefer opposite spinner directions.

Perhaps an overall setting / option could be considered in the MiSTer system itself?

**Comment by HerrBerzerk** [comment]
For the Spinner Option workd perfect. And this is the only arcade game where spinner (or even trakball) works perfect. Great Job! Can't you take a look at the other spinner or trakball games like centipede or circus or breakout and fix them?

**Comment by dfilskov** [comment]
Which game(s) has reverse option now?

**Comment by neosquid** [comment]
Old issue, ~ swapping wires did fix issue.
