### ISSUE TITLE
Orientation setting doesn't work with VGA/DB15 output

### ISSUE THREAD

**Issue by sofakng** [Ace9921/Arcade-Arkanoid_MISTer#4]
I'm using the MiSTer and the I/O board with the DB15 (VGA) connected to a 15 kHz TV using the [ypbpr=0] setting to output component video.

The Arkanoid core was a setting for Orientation (Horz / Vert) but both settings don't change the orientation.  (the output stays "sideways" [vertical?])

**Comment by sorgelig** [comment]
it's only for HDMI output.
Can be used on VGA when vga_scaler=1

**Comment by sofakng** [comment]
Thanks very much for the information.
